CMake (#10)
### Changes
* Added all necessary CMake files.
  * Shared library target
  * Optional unit test target
  * Optionally include compiler warnings.
* Added documentation for building and installing.
* Closes #4

### Additional Context
Using `IEX_EXTRA_COMPILE_OPTIONS` option with an illegal cast:
```c++
int a = (int)1.5;
```
Causes compilation to fail:
```
/home/antony/Drive/Programming/iex/iex/iex.cc:24:16: error: use of old-style cast to ‘int’ [-Werror=old-style-cast]
   24 |   int a = (int)1.5;
      |                ^~~
      |           --------
      |           static_cast<int> (1.5)
cc1plus: all warnings being treated as errors
```
Running unit test after compiling with `IEX_BUILD_TESTING` option:
```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from iex
[ RUN      ] iex.init_test
[       OK ] iex.init_test (0 ms)
[----------] 1 test from iex (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (0 ms total)
[  PASSED  ] 1 test.
```